import Head from 'next/head';
import styles from '../styles/Home.module.css';
import React, { Component } from 'react';

class App extends Component {
	constructor(props) {
		super(props);
	}

	render() {
		return (
			<div className={styles.container}>
				<Head>
					<title>HCI Sci Discord Bot</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon.ico" />
						
					<div class="topnav" id="myTopnav">
					 <a href="https://link.to/teacher/portal" class="active">Home</a>
  					 <a href="./credits" class="active">Home</a>
 					 <a href="./contirbuting">News</a>
 					 <a href="./description">Contact</a>
  					 <a href="./commands">About</a>
 					 <a href="javascript:void(0);" class="icon" onclick="myFunction()">
   					  <i class="fa fa-bars"></i>
 					 </a>
					</div>

					.topnav {
  					 background-color: #333;
  					 overflow: hidden;
					}

					.topnav a {
 					 float: left;
  					 color: #f2f2f2;
					 text-align: center;
  					 padding: 14px 16px;
  					 text-decoration: none;
  					 font-size: 17px;
					}

					.topnav a:hover {
  					 background-color: #ddd;
  					 color: black;
					}

					.topnav a.active {
 					 background-color: #04AA6D;
 					 color: white;
					}
				</Head>

				<main className={styles.main}>
					<h1 className={styles.title}>The HCI Discord Science Bot</h1>

					<p className={styles.description}>
						Join this <a className={styles.link} href='https://discord.gg/RtrGUaTVcS'>server</a> to use the bot!
					</p>
					
					<div className={styles.grid}>
						<a href='./commands' className={styles.card}>
							<h2>Commands</h2>
							<p>View the all the bot commands here!</p>
						</a>
						<a href='./description' className={styles.card}>
							<h2>Read More</h2>
							<p>Read the description of the bot and etc.</p>
						</a>
						<a href='./contributing' className={styles.card}>
							<h2>Contributing Guide</h2>
							<p>Contribute to this site, the bot, database server or the Teacher{String.fromCharCode(39)}s Portal!</p>
						</a>
						<a href='https://link.to/teacher/portal' className={styles.card}>
							<h2>Teacher{String.fromCharCode(39)}s Portal (Link to be added)</h2>
							<p>Login to the Teacher{String.fromCharCode(39)}s Portal (Teachers only{/* , if you are a student do not even think of it */})</p>
						</a>
						<a href='./credits' className={styles.card}>
							<h2>Credits</h2>
							<p>The names and contributions of our developer team!</p>
						</a>
					</div>
				</main>

				<footer className={styles.footer}>
          Powered by <a href='https://nextjs.org'>Next.js</a> and served by GitHub Pages {/* IDK why I put the in brackets but ok */}
				</footer>
			</div>
		);
	}
}

export default App;
